### ISSUE TITLE
is this code base build properly

### ISSUE THREAD

**Issue by atmohsin** [stemmlerjs/white-label#2]
Hi,
I am trying to build this code, it is giving lot of error message, 

Please let me know is this latest code base, 

Thanks
Mohsin

**Comment by stemmlerjs** [comment]
@atmohsin Hey, I'm still working on it! The majority of the code in here at the moment is meant to be supplementary content to the blog, and the upcoming DDD course I'm working on. 

It'll shape up soon and I'll update it with notes on how to run the project.

Cheers
